name: FinAI Continuous Integration

on:
  push:
    branches:
      - develop
      - main

  pull_request:
    branches:
      - develop
      - main

jobs:
  flutter-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mobile_app

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install Dependencies
        run: flutter pub get

      - name: Analyze Project
        run: flutter analyze

      - name: Run Tests
        run: flutter test
        
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  google_fonts: ^6.3.0
  intl: ^0.20.2